/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#bacac1',
        'on-tertiary': '#472a00',
        'error': '#ffb4ab',
        'tertiary-fixed': '#ffddb8',
        'secondary-container': '#0566d9',
        'surface-variant': '#2d3449',
        'surface-tint': '#2fe0aa',
        'surface-container-low': '#131b2e',
        'inverse-primary': '#006c4f',
        'on-tertiary-fixed': '#2a1700',
        'error-container': '#93000a',
        'on-primary-container': '#00533c',
        'surface-bright': '#31394d',
        'secondary': '#adc6ff',
        'primary-fixed-dim': '#2fe0aa',
        'on-secondary': '#002e6a',
        'primary-fixed': '#59fdc5',
        'inverse-on-surface': '#283044',
        'inverse-surface': '#dae2fd',
        'tertiary-container': '#fda417',
        'tertiary-fixed-dim': '#ffb95f',
        'on-secondary-fixed-variant': '#004395',
        'on-error': '#690005',
        'on-secondary-container': '#e6ecff',
        'on-surface': '#dae2fd',
        'on-primary': '#003828',
        'outline-variant': '#3c4a43',
        'secondary-fixed-dim': '#adc6ff',
        'background': '#0b1326',
        'on-primary-fixed': '#002116',
        'on-primary-fixed-variant': '#00513b',
        'primary-container': '#00d09c',
        'surface-container-lowest': '#060e20',
        'primary': '#44edb7',
        'on-background': '#dae2fd',
        'surface-container-high': '#222a3d',
        'tertiary': '#ffc98a',
        'on-tertiary-fixed-variant': '#653e00',
        'secondary-fixed': '#d8e2ff',
        'on-error-container': '#ffdad6',
        'outline': '#85948c',
        'on-secondary-fixed': '#001a42',
        'surface-dim': '#0b1326',
        'surface-container-highest': '#2d3449',
        'on-tertiary-container': '#673f00',
        'surface': '#0b1326',
        'surface-container': '#171f33',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
      spacing: {
        'base': '4px',
        'xs': '8px',
        'sm': '16px',
        'md': '24px',
        'lg': '40px',
        'xl': '64px',
        'gutter': '20px',
      },
      fontFamily: {
        'mono-data': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Plus Jakarta Sans', 'sans-serif'],
        'title-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Outfit', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Outfit', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
